[tool.isort]
profile = "black"

[tool.mypy]
exclude = "simulation/"
warn_unused_configs = true
disallow_subclassing_any = true
disallow_untyped_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true
disallow_untyped_calls = true
