name: Run commands main
on: [push]

env:
  PYTHONPATH: .

jobs:
  run_commands:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run:
          - 3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: "3.9"
      - run: pip install pipenv
      - run: pipenv sync --dev
      
      - run: |
          a="${{matrix.run}}"

          declare -A lookup

          lookup["1"]="0.92059746"
          lookup["2"]="0.41765568"
          lookup["3"]="0.06870228"
          lookup["4"]="0.13841037"
          lookup["5"]="0.27698414"
          lookup["6"]="0.84976992"
          lookup["7"]="0.77176185"
          lookup["8"]="0.59919061"
          lookup["9"]="0.33800352"
          lookup["10"]="0.67774452"
          theInfluence=${lookup[$a]}
          echo $theInfluence

            pipenv run python -m simulation "./input/scottish_stratified_sample_1.parquet"  "./scot_sc1_${{ matrix.run }}.jsonl.gz"    --air-source-heat-pump-price-discount-date 2023-01-01:0.3
      - name: Archive jsonl
        uses: actions/upload-artifact@v3
        with:
          name: scot_sc1_jsonl
          path: |
            ./scot_sc1_${{ matrix.run }}.jsonl.gz
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - run: |
          pipenv run python convert_history_to_dataframes_for_github_actions.py ${{ matrix.run }}
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: scot_sc1_results
          path: |
            ./scot_sc1_${{ matrix.run }}_agent_history.feather
            ./scot_sc1_${{ matrix.run }}_model_history.feather