name: Run commands social network influence importance
on: [push, workflow_dispatch]

env:
  PYTHONPATH: .

jobs:
  run_commands:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parameters:
        - 6
        - 3
        run:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: "3.9"
      - run: pip install pipenv
      - run: pipenv sync --dev
      
      - run: |
          a="${{matrix.parameters}}"

          declare -A lookup

          lookup["6"]="0.33800352"
          lookup["3"]="0.67774452"
          theInfluence=${lookup[$a]}
          echo $theInfluence

          pipenv run python -m simulation "./input/scottish_stratified_sample_1_with_network_half.parquet"  "./influence_importance_sc1_${{ matrix.parameters }}_${{ matrix.run }}.jsonl.gz"  --air-source-heat-pump-price-discount-date 2023-01-01:0.3 --social-influence-importance $theInfluence
          pipenv run python -m simulation "./input/scottish_stratified_sample_1_with_network_half.parquet"  "./influence_importance_sc2_${{ matrix.parameters }}_${{ matrix.run }}.jsonl.gz"  --intervention boiler_upgrade_scheme --intervention gas_oil_boiler_ban --gas-oil-boiler-ban-date 2035-01-01 --gas-oil-boiler-ban-announce-date 2025-01-01 --heat-pump-awareness 0.5 --air-source-heat-pump-price-discount-date 2023-01-01:0.3 --price-gbp-per-kwh-gas 0.0589 --price-gbp-per-kwh-electricity 0.1494 --social-influence-importance $theInfluence

      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: influence_importance_sc1_results
          path: |
            ./influence_importance_sc1_${{ matrix.parameters }}_${{ matrix.run }}.jsonl.gz
            ./influence_importance_sc2_${{ matrix.parameters }}_${{ matrix.run }}.jsonl.gz
          if-no-files-found: error
