name: Run commands green attitudes
on: [push]

env:
  PYTHONPATH: .

jobs:
  run_commands:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parameters:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10 
        run:
          - 1
          - 2
          - 3
          - 4
          - 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: "3.9"
      - run: pip install pipenv
      - run: pipenv sync --dev
      
      - run: |
          a="${{matrix.parameters}}"

          declare -A lookup

          lookup["1"]="0.92059746"
          lookup["2"]="0.41765568"
          lookup["3"]="0.06870228"
          lookup["4"]="0.13841037"
          lookup["5"]="0.27698414"
          lookup["6"]="0.84976992"
          lookup["7"]="0.77176185"
          lookup["8"]="0.59919061"
          lookup["9"]="0.33800352"
          lookup["10"]="0.67774452"
          theInfluence=${lookup[$a]}
          echo $theInfluence

            pipenv run python -m simulation "./input/scottish_stratified_sample_1_with_network_half.parquet"  "./green_attitudes_lhs_${{matrix.parameters}}_${{matrix.run}}.jsonl.gz"  --intervention rhi --start-date 2012-01-01 --steps 96 --heat-pump-installer-annual-growth-rate 0 --green-attitudes-influence $theInfluence
      - name: Archive jsonl
        uses: actions/upload-artifact@v3
        with:
          name: green_attitudes_rhi_jsonl
          path: |
           ./green_attitudes_lhs_${{matrix.parameters}}_${{matrix.run}}.jsonl.gz